### ISSUE TITLE
Outline remaining time with interns and specific contributions to SSEEP analyses.

### ISSUE THREAD

**Issue by mguyant** [thefaylab/sseep#2]
Acceptance criteria: Approved morning and afternoon task blocks for Week 3 and Week 4 for both interns that address remaining SSEEP and SciComm needs.

**Comment by AngeliaMiller** [comment]
Intern analyses can be found in the intern branch of the wind-analysis_old repo [here](https://github.com/thefaylab/wind-analysis_old/tree/intern). However, the code has since been merged into the ongoing and current analyses being produced in the [sseep-analyses repo](https://github.com/thefaylab/sseep-analysis).
